config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :selected_items, only: [ :show, :create, :index , :destroy ]
  # Defines the root path route ("/")
  # root "posts#index"
  resources :categories, only: [:show, :index]
  resources :items, only: [:show, :new, :create, :index, :edit, :update, :destroy]
  resources :purchases, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_one_attached :photo
  validates :price, numericality: { greater_than: 0 }
  validates :photo, attached: true

  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :name, :description],
  associated_against: {
    category: [ :name, :description ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
end

app/models/purchaseditem.rb
class Purchaseditem < ApplicationRecord
  belongs_to :item
  belongs_to :purchase
end

app/models/selecteditem.rb
class Selecteditem < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :selecteditem
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to item_path(@item), notice: 'Item created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @items = Item.all
    if params[:query].present?
      sql_subquery = <<~SQL
        items.name @@ :query
        OR items.description @@ :query
        OR categories.name @@ :query
      SQL
      @items = @items.joins(:category).where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path(@item), notice: 'Item updated!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, notice: 'Item deleted'
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :quantity, :price, :category_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @categories = Category.all
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
    @purchase = Purchase.new
    @selected_items = Selecteditem.where(user: current_user)
    @total_price = 0
    @selected_items.each do |selected_item|
      @total_price += selected_item.quantity * selected_item.item.price
    end
  end

  def create
  end
end

app/controllers/selected_items_controller.rb
class SelectedItemsController < ApplicationController
  def index
    @selected_items = Selecteditem.where(user: current_user)
  end

  def show
    @selected_item = Selecteditem.find(params[:id])
  end

  def new
    @items = Item.find(params[:item_id])
    @selected_item = Selecteditem.all
  end

  def create
    @item = Item.find(params[:item_id])
    @selected_item = Selecteditem.new(quantity: 1, item: @item, user: current_user)
    @selected_item.save
    redirect_to item_path(@item)
  end

  def destroy
    @selected_item = Selecteditem.find(params[:id])
    @selected_item.destroy
    redirect_to selected_items_path, notice: "Selected item was successfully removed from your cart."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.erb
<div class ="image-div-snoop"style="text-align: center;">
  <%= image_tag "snoop.png", alt: "Logo", width: 100, style: "margin-bottom: 5px; display: inline-block;" %>
</div>

<div class="container">
  <%= link_to "Back", :back %>
  <div class="row justify-content-center">
    <h5 class="card-title"><%= @category.name %></h5>
    <% @category.items.each do |item| %>
      <%= render "items/item-card", item: item %>
    <% end %>
  </div>
</div>

app/views/items/_item-card.html.erb
<div class="col-6 px-0">
  <%=link_to item_path(item), class: "no-link-style" do %>
    <div class="card-item" text-decoration="none">
      <div class="card-body">
        <div class="card" style="border-radius: 10px;">
          <div class="card-body">
            <%= cl_image_tag item.photo.key, alt: "Fruit", class: "fruit-image" %>
            <h6 class="card-subtitle mb-2 text-muted"><strong><%= item.name %></strong></h6>
            <p class="item-price"><strong>€<%= item.price %></strong></p>
            <div class="d-flex justify-content-end">
              <button class="btn btn-success btn-sm" type="button"><strong>+</strong></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<div class="container">
  <div style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh;">
    <div style="margin-bottom: 20px;">
      <%= image_tag "snoop-market-logo.png", alt: "Logo", width: 100, style: "vertical-align: middle;" %>
    </div>
    <%= simple_form_for(@item) do |f| %>
      <%= f.input :name %>
      <%= f.input :category_id, collection: Category.all %>
      <%= f.input :quantity %>
      <%= f.input :price %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Update item", class: "btn-green-primary" %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="header text-center">
  <%= image_tag "snoop.png", alt: "Logo", width: 100, style: "margin-bottom: 5px; margin-top: 30px" %>
</div>

<div class="search-bar text-center">
  <%= form_with url: items_path, method: :get, class: "search-form" do %>
    <div class="input-wrapper">
      <%= text_field_tag :query,
            params[:query],
            class: "search-input form-control",
            placeholder: "What can we help you find?"
        %>
      <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="row justify-content-center">
    <% if @items.any? %>
      <% @items.each do |item| %>
        <%= render "item-card", item: item %>
      <% end %>
    <% else %>
      <p>No results found. Sorry :(</p>
    <% end %>
  </div>
</div>

<div class="navbar fixed-bottom">
  <div class="button-column">
    <i class="fa-solid fa-shop"></i>
      <%= link_to root_path, class: "no-link-style" do %>
      <span>Shop</span>
    <% end %>
  </div>
  <div class="button-column">
    <i class="fa-solid fa-cart-shopping"></i>
      <%= link_to selected_items_path, class: "no-link-style" do %>
        <span>Cart</span>
      <% end %>
  </div>
  <div class="button-column">
    <i class="fa-solid fa-user"></i>
      <%= link_to user_session_path, class: "no-link-style" do %>
      <span>Login</span>
      <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
  <div style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh;">
    <div style="margin-bottom: 20px;">
      <%= image_tag "snoop-market-logo.png", alt: "Logo", width: 100, style: "vertical-align: middle;" %>
    </div>
    <%= simple_form_for(@item) do |f| %>
      <%= f.input :name %>
      <%= f.input :category_id, collection: Category.all %>
      <%= f.input :quantity %>
      <%= f.input :price %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Create item", class: "btn-green-primary" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<%# First we should be putting the item image but idk how yet %>
<div class="card-cover">
  <%= cl_image_tag @item.photo.key  %>
</div>
<div class="container item-show" style="margin-bottom: 100px;">
  <%= link_to :back, class: 'back-button me-2' do %> <!-- link_to 'prefix selected_items' -->
    <i class="fa-solid fa-chevron-left"></i>
  <% end %>
  <%= link_to "Edit", edit_item_path(@item) %>
  <%= link_to "Delete", item_path(@item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
  <div class="item-header">
    <div class="item-header-top">
      <div class="item-header-label">
        <h1><%= @item.name %></h1>
        <p>1kg, Price</p> <!-- I have to make it dynamic but we don't have nothing to do it -->
      </div>
      <div class="item-header-bookmark">
        <!-- <%= link_to %> I should be having a method and a route to bookmark -->
        ♡
      </div>
    </div>
    <div class="item-header-bottom">
      <div class="increase-decrease-unit">
        <button class="btn decrease-unit">-</button>
        1
        <button class="btn increase-unit">+</button>
      </div>
      <div class="unit-price">
        <h1>€<%= @item.price %></h1>
      </div>
    </div>
  </div>
  <div data-controller="card" class="item-card">
    <div class="item-card-section">
      <div class="item-card-header">
        <h5 class="card-title" id="item">Product Detail</h5>
        <button data-action="click->card#toggle" class="btn"></button> <%# Add dropdown ">" icon that turns 90 degrees down when active %>
      </div>
      <div data-target="card.body" class="card-body">
        <p><%= @item.description %></p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Recusandae dolores molestiae ipsam veritatis pariatur rem illum accusamus libero sed iure voluptatum aliquam iste laboriosam laborum, consectetur omnis quod facere nisi.</p>
      </div>
    </div>
    <div class="item-card-section">
      <div class="item-card-header">
        <h5 class="card-title" id="item">Nutrition Information</h5>
        <button data-action="click->card#toggle" class="btn">></button> <%# Add dropdown ">" icon that turns 90 degrees down when active %>
      </div>
      <div data-target="card.body" class="card-body" style="display: none;">
        <p><%# @item.nutritional (CREATE) %></p>
      </div>
    </div>
    <div class="item-card-section">
      <div class="item-card-header">
        <h5 class="card-title" id="item">Rating</h5>
        <div class="rating">
          <div class="stars">
            ★★★★★ <%# We should be making a component that according to x rating shows x stars %>
          </div>
          <button data-action="click->card#toggle" class="btn">></button> <%# Add dropdown ">" icon that turns 90 degrees down when active %>
        </div>
      </div>
      <div data-target="card.body" class="card-body" style="display: none;">
        <p><%# @item.nutritional (CREATE) %></p>
      </div>
    </div>
  </div>
  <div id="add-to-basket-btn">
    <%= link_to "Add To Basket", selected_items_path(item_id: @item), data: {turbo_method: :post}, class: "btn-green-primary" %>
  </div>
</div>

app/views/layouts/_navbar-footer.html.erb
<div class="navbar fixed-bottom">
  <div class="button-column">
    <i class="fa-solid fa-shop"></i>
    <%= link_to root_path, class: "no-link-style" do %>
      <span>Shop</span>
    <% end %>
  </div>
  <div class="button-column">
    <% if current_user && current_user.admin? %>
      <i class="fa-solid fa-plus"></i>
      <%= link_to new_item_path, class: "no-link-style" do %>
        <span>Inventory</span>
      <% end %>
    <% else %>
      <i class="fa-solid fa-cart-shopping"></i>
      <%= link_to selected_items_path, class: "no-link-style" do %>
        <span>Cart</span>
      <% end %>
    <% end %>
  </div>
  <div class="button-column">
    <i class="fa-solid fa-user"></i>
    <%= link_to user_session_path, class: "no-link-style" do %>
      <span>Login</span>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnoopMarketApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="mb-5">
      <%= yield %>
    </div>
    <% unless params[:controller] == "items" && params[:action] == 'show' %>
      <%= render "layouts/navbar-footer" %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="header-buttons-container">
  <%= link_to destroy_user_session_path, class: "no-link-style", data: {turbo_method: :delete} do %>
    <i class="fa-regular fa-user"></i>
    <span>Sign out</span>
  <% end %>
</div>

<div class="header text-center">
  <%= image_tag "snoop.png", alt: "Logo", width: 100, style: "margin-bottom: 5px; margin-top: 30px" %>
    <div>
      <div style="display: inline-block;">
        <i class="fa-solid fa-location-dot"></i> <p style="display: inline;">Barcelona, Spain</p>
      </div>
    </div>
</div>

<div class="search-bar text-center">
  <%= form_with url: items_path, method: :get, class: "search-form" do %>
    <div class="input-wrapper">
      <%= text_field_tag :query,
            params[:query],
            class: "search-input form-control",
            placeholder: "What can we help you find?"
        %>
      <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
    </div>
  <% end %>
</div>

<div class="container" id="home_container_id">
  <div class="row justify-content-center">
    <% @categories.each_slice(2) do |category_row| %>
      <div class="col-sm-4 my-3">
        <div class="d-flex justify-content-around">
          <% category_row.each do |category| %>
            <%= link_to category_path(category), class: "no-link-style" do %>
              <div class="card-category <%= category.color %>">
                <%= image_tag("categories/#{category.name}.png", alt: category.name, class: "card-image") %>
                <div style="margin-bottom: 15px;"><%= category.name %></div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/purchases/new.html.erb
<div class="container">
  <div class="section-header">
    <%= link_to :back, class: 'back-button' do %> <!-- link_to 'prefix selected_items' -->
      <i class="fa-solid fa-chevron-left"></i>
    <% end %>
    <h2>Checkout</h2>
  </div>

  <div class="section-body">
    <div class="purchase-form">
      <%= simple_form_for @purchase do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :address %>
        <div class="total-cost-collapse">
          <div class="card-collapse">
            <div class="card-label">
              <p class="card-collapse-label">Total cost</p>
              <div class="total-cost-expand">
                <p class="total-cost"><%= @total_price %>€</p>
                <%= link_to '#', class: 'expand-button' do %> <!-- link_to '/items/:item_id/selected_items' -->
                  <i class="fa-solid fa-chevron-right" id="expand-button"></i>
                <% end %>
              </div>
            </div>
            <div class="card-details">
              <ul class="cart-items">
                <% @selected_items.each do |selected_item| %>
                  <li>
                    <div class="item-container">
                      <span class="item-name"><%= selected_item.item.name %></span>
                      <span class="subtotal-per-item"><%= selected_item.quantity * selected_item.item.price %>€</span>
                    </div>
                  </li>                
                <% end %>
                

              </ul>
            </div>
          </div>
        </div>
        <div class="terms-and-conditions">
          <p class="terms">By placing an order you agree to our <span>Terms</span> and <span>Conditions</span></p>
        </div>
        <div class="checkout-button-container">
          <%= f.button :submit, value: "Place order", class: "checkout-button", data: { toggle: "modal", target: "#confirmPurchase" } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="confirmPurchase" tabindex="-1" role="dialog" aria-labelledby="confirmPurchaseLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmPurchaseLabel">Purchase confirmed</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Congratulations for your purchase, you can expect the delivery to happen within the next 48h. 😀
      </div>
      <div class="modal-footer">
        <%= link_to "OK", root_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/selected_items/index.html.erb
<div class="container">
  <div class ="image-div-snoop"style="text-align: center;">
    <%= image_tag "snoop.png", alt: "Logo", width: 100, style: "margin-bottom: 5px; display: inline-block;" %>
  </div>
  <h1 class="card-text">My Cart</h1>
  <div class="container-basket">
    <% total_price = 0 %>
    <% quantity = 1%>
    <% if @selected_items.present? %>
      <% item_counts = @selected_items.group_by(&:item_id).transform_values(&:count) %>
      <% item_counts.each do |item_id, count| %>
        <% selected_item = @selected_items.find { |si| si.item_id == item_id } %>
        <div class=" card-basket">
          <div>
            <%= cl_image_tag selected_item.item.photo.key, alt: "Fruit", class: "basket-images" %>
          </div>
          <div>
            <h6><%= selected_item.item.name %> (<%= count %> item/s)</h6>
            <p><%= selected_item.item.price %>€</p>
              <div>
                <button class="btn btn-success btn-sm" type="button"><strong>-</strong></button>
                <%=quantity%>
                <button class="btn btn-success btn-sm" type="button"><strong>+</strong></button>
              </div>
                <div class="btn btn-delete" type="button">
                <strong><%= link_to "Remove Item", selected_item_path(selected_item.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"delete-text"%></strong>
                <%# .id not mandatory, Rails will intuitively fetch the id if just selected_item is passed %>
                </div>
          </div>
        </div>
        <% total_price += selected_item.item.price * count %>
      <% end %>
      <div class="row">
        <div class="col-sm-12 total-price">
          <p>Total: <span><%= total_price.round(2) %>€</span></p>
        </div>
      </div>

    <% else %>
      <p>Your basket is empty.</p>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <button class= "btn-green-primary" type="button"><strong><%=link_to "Go to Checkout", new_purchase_path,  class: "checkout-button" %></strong></button>
    </div>
  </div>
</div>

<div class="navbar fixed-bottom">
  <div class="button-column">
    <i class="fa-solid fa-shop"></i>
      <%= link_to root_path, class: "no-link-style" do %>
      <span>Shop</span>
    <% end %>
  </div>
  <div class="button-column">
    <i class="fa-solid fa-cart-shopping"></i>
      <%= link_to selected_items_path, class: "no-link-style" do %>
        <span>Cart</span>
      <% end %>
  </div>
  <div class="button-column">
    <i class="fa-solid fa-user"></i>
      <%= link_to user_session_path, class: "no-link-style" do %>
      <span>Login</span>
      <% end %>
  </div>
</div>